#!/usr/bin/env bash
# Deploy Azure resources for the sentence-citation-prototype and write a
# local .env with endpoints + keys. Idempotent: re-running updates the
# existing resources and refreshes .env.
#
# Requires: az CLI logged in (`az login`) to a subscription with Azure
# OpenAI access in the target region.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

: "${RG:=rg-sentcite-dev}"
: "${LOCATION:=eastus2}"
: "${NAME_PREFIX:=sentcite}"

echo "==> Resource group:  $RG"
echo "==> Location:        $LOCATION"
echo "==> Name prefix:     $NAME_PREFIX"

az account show -o none >/dev/null 2>&1 || {
  echo "Not logged in. Run: az login" >&2
  exit 1
}

az group create -n "$RG" -l "$LOCATION" -o none

DEPLOY_NAME="sentcite-$(date +%s)"
echo "==> Starting deployment $DEPLOY_NAME"
az deployment group create \
  -g "$RG" \
  -n "$DEPLOY_NAME" \
  --template-file "$HERE/main.bicep" \
  --parameters namePrefix="$NAME_PREFIX" location="$LOCATION" \
  -o none

get_out() {
  az deployment group show -g "$RG" -n "$DEPLOY_NAME" \
    --query "properties.outputs.$1.value" -o tsv
}

STORAGE=$(get_out storageAccountName)
DOCINTEL_NAME=$(get_out docIntelName)
DOCINTEL_ENDPOINT=$(get_out docIntelEndpoint)
SEARCH_NAME=$(get_out searchName)
SEARCH_ENDPOINT=$(get_out searchEndpoint)
OPENAI_NAME=$(get_out openaiName)
OPENAI_ENDPOINT=$(get_out openaiEndpoint)
CHAT_DEPLOY=$(get_out openaiChatDeployment)
EMBED_DEPLOY=$(get_out openaiEmbeddingDeployment)

echo "==> Fetching keys"
DOCINTEL_KEY=$(az cognitiveservices account keys list -g "$RG" -n "$DOCINTEL_NAME" --query key1 -o tsv)
OPENAI_KEY=$(az cognitiveservices account keys list -g "$RG" -n "$OPENAI_NAME" --query key1 -o tsv)
SEARCH_KEY=$(az search admin-key show -g "$RG" --service-name "$SEARCH_NAME" --query primaryKey -o tsv)
STORAGE_CS=$(az storage account show-connection-string -g "$RG" -n "$STORAGE" --query connectionString -o tsv)

ENV_FILE="$REPO_ROOT/.env"
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
  echo "==> Existing .env backed up"
fi

cat > "$ENV_FILE" <<EOF
# Generated by infra/deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not commit. Regenerate by re-running infra/deploy.sh.

AZURE_STORAGE_ACCOUNT=$STORAGE
AZURE_STORAGE_CONTAINER_RAW=raw-pdfs
AZURE_STORAGE_CONTAINER_PARSED=parsed
AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CS

AZURE_DOCINTEL_ENDPOINT=$DOCINTEL_ENDPOINT
AZURE_DOCINTEL_KEY=$DOCINTEL_KEY

AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_SEARCH_API_KEY=$SEARCH_KEY
AZURE_SEARCH_INDEX_CHUNKS=tax-chunks
AZURE_SEARCH_INDEX_SENTENCES=tax-sentences

AZURE_OPENAI_ENDPOINT=$OPENAI_ENDPOINT
AZURE_OPENAI_API_KEY=$OPENAI_KEY
AZURE_OPENAI_API_VERSION=2024-10-21
AZURE_OPENAI_CHAT_DEPLOYMENT=$CHAT_DEPLOY
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=$EMBED_DEPLOY
EOF
chmod 600 "$ENV_FILE"

echo ""
echo "Deployment complete. Wrote $ENV_FILE"
echo "  Storage:          $STORAGE"
echo "  Doc Intelligence: $DOCINTEL_NAME  ($DOCINTEL_ENDPOINT)"
echo "  AI Search:        $SEARCH_NAME    ($SEARCH_ENDPOINT)"
echo "  Azure OpenAI:     $OPENAI_NAME    ($OPENAI_ENDPOINT)"
echo "    chat:           $CHAT_DEPLOY"
echo "    embedding:      $EMBED_DEPLOY"
